
# =============================
# ExalinkHub - docker-compose.dev.yml (DESARROLLO)
# ---------------------------------------------
# Uso: docker compose -f docker-compose.dev.yml up -d
#
# - Expone puertos para acceso externo (localhost:9002, 2221, 2223, 2224)
# - Todos los volúmenes usan rutas relativas multiplataforma (./...)
# - Funciona en Windows y Linux, en cualquier carpeta
# - Frontend accesible en http://localhost:9002
# - Permite hot reload si el frontend lo soporta
# - Los servicios pueden ser accedidos desde el host
# =============================


services:
  # Frontend para desarrollo (opcional, expone 0.0.0.0:9002)
  frontend:
    build:
      context: ./frontend-build
      dockerfile: Dockerfile
    image: exalink/frontend:dev
    container_name: exalink-frontend-dev
    restart: unless-stopped
    ports:
      - "9002:3000"  # Acceso externo en 0.0.0.0:9002
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./DB:/app/DB:rw
      - ./data:/app/data:rw
      - ./MEDIA:/app/MEDIA:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lpr-network
    depends_on:
      - matriculas-listener
      - conteo-backend
      - notificaciones-backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.exalink.service=frontend-dev"

  # Backend LPR con código montado
  matriculas-listener:
    build:
      context: ./backend/Matriculas/listener
      dockerfile: Dockerfile.dev
    container_name: matriculas-listener-dev
    restart: unless-stopped
    ports:
      - "${LPR_PORT:-2221}:2221"
    environment:
      - DB_DIR=/app/DB
      - MEDIA_DIR=/app/MEDIA
      - LOG_DIR=/app/LOG
      - CONF_PATH=/app/matriculas.conf
      - PYTHONPATH=/app
    # Montar código fuente para desarrollo
    volumes:
      - ./backend/Matriculas/listener:/app:cached
      - ./backend/Matriculas/matriculas.conf:/app/matriculas.conf:ro
      # Montar datos persistentes
      - ./DB:/app/DB:rw
      - ./MEDIA:/app/MEDIA:rw
      - ./LOG:/app/LOG:rw
    networks:
      - lpr-network
    labels:
      - "com.exalink.service=matriculas-listener-dev"

  # Backend de conteo con código montado
  conteo-backend:
    build:
      context: ./backend/conteo
      dockerfile: Dockerfile.dev
    container_name: exalink-conteo-backend-dev
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PYTHONPATH=/app
    ports:
      - "${CONTEO_PORT:-2223}:8012"
    # Montar código fuente y configuración
    volumes:
      # Mount the source code for development
      - ./backend/conteo:/app:cached
      - ./backend/conteo/config:/app/config:rw
      # Ensure the database folder is explicitly mounted so /app/DB exists inside the container
      # Use host bind for local dev and named volume as fallback
      - ./backend/conteo/DB:/app/DB:rw
    networks:
      - lpr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "com.exalink.service=conteo-backend-dev"

  # Backend de notificaciones con código montado
  notificaciones-backend:
    build:
      context: ./backend/notificaciones
      dockerfile: Dockerfile.dev
    container_name: exalink-notificaciones-backend-dev
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PYTHONPATH=/app
    ports:
      - "${NOTIFICACIONES_PORT:-2224}:8022"
    # Montar código fuente y configuración
    volumes:
      - ./backend/notificaciones:/app:cached
      - ./backend/notificaciones/config:/app/config:rw
    networks:
      - lpr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8022/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "com.exalink.service=notificaciones-backend-dev"

  # Redis (igual que en producción)
  lpr-redis:
    image: redis:7-alpine
    container_name: exalink-lpr-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-exalink123}
    volumes:
      - lpr-redis-data:/data
    networks:
      - lpr-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.exalink.service=lpr-redis-dev"

  # Proxy Nginx (opcional para desarrollo)
  lpr-proxy:
    image: nginx:alpine
    container_name: exalink-lpr-proxy-dev
    restart: unless-stopped
    ports:
      - "${LPR_HTTPS_PORT:-2443}:443"
      - "${LPR_HTTP_PORT:-2280}:80"
    # Configuración Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


  # Monitor (opcional para desarrollo)
  lpr-monitor:
    image: prom/node-exporter:latest
    container_name: exalink-lpr-monitor-dev
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - lpr-network
    profiles:
      - monitoring
    labels:
      - "com.exalink.service=lpr-monitor-dev"

volumes:
  lpr-data:
    driver: local
    labels:
      - "com.exalink.volume=lpr-data"
  lpr-logs:
    driver: local
    labels:
      - "com.exalink.volume=lpr-logs"
  lpr-redis-data:
    driver: local
    labels:
      - "com.exalink.volume=lpr-redis-data"
  counting-db:
    driver: local
    labels:
      - "com.exalink.volume=counting-db"
  config-db:
    driver: local
    labels:
      - "com.exalink.volume=config-db"

networks:
  lpr-network:
    driver: bridge
    name: exalink-lpr-network-dev
    labels:
      - "com.exalink.network=lpr-internal-dev"
  public:
    driver: bridge
    name: exalink-public-dev
    labels:
      - "com.exalink.network=public-dev"